// Supplement export — professional PDF from a v2 comparison report.
// Design: docs/estimate-comparison-redesign.md §6. The client sends the
// report it already holds; every number in the PDF was computed
// deterministically by the engine, and match provenance is printed so the
// packet is defensible.
import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import PDFDocument from 'pdfkit'
import { authOptions } from '@/lib/auth'

export const dynamic = 'force-dynamic'

interface ExportItem {
  room: string
  code: string | null
  description: string
  mineQty: string
  carrierQty: string
  deltaCents: number
}

const fmt = (cents: number): string =>
  `${cents < 0 ? '-' : ''}$${(Math.abs(cents) / 100).toLocaleString('en-US', { minimumFractionDigits: 2 })}`

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }
    const report = await request.json()
    const buffer = await renderPdf(report)
    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="Supplement_${(report.summary?.claimNumber ?? 'estimate').replace(/[^\w-]/g, '_')}.pdf"`,
      },
    })
  } catch (error) {
    console.error('[Export v2] Failed:', error)
    return NextResponse.json({ error: 'Export failed' }, { status: 500 })
  }
}

/* eslint-disable @typescript-eslint/no-explicit-any -- report is the client's
   CompareReport JSON; shapes are validated by usage below */
async function renderPdf(report: any): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 46, size: 'LETTER' })
  const chunks: Buffer[] = []
  doc.on('data', (chunk: Buffer) => chunks.push(chunk))
  const done = new Promise<Buffer>((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))))

  const summary = report.summary ?? {}

  // Header
  doc.font('Helvetica-Bold').fontSize(18).text('Estimate Difference Report')
  doc.moveDown(0.2)
  doc.font('Helvetica').fontSize(10).fillColor('#555555')
  doc.text(
    [
      summary.clientName ?? 'Estimate comparison',
      summary.claimNumber ? `Claim ${summary.claimNumber}` : null,
      `Prepared ${new Date().toLocaleDateString('en-US')}`,
    ]
      .filter(Boolean)
      .join(' · ')
  )
  doc.moveDown(0.8)

  // Totals
  doc.fillColor('#000000').font('Helvetica-Bold').fontSize(13)
  doc.text(`Total difference: ${summary.delta ?? ''}${(summary.deltaRcvCents ?? 0) >= 0 ? ' in our favor' : ''}`)
  doc.font('Helvetica').fontSize(10).fillColor('#333333')
  doc.text(`Our estimate: ${summary.mineTotal ?? ''}    Carrier estimate: ${summary.carrierTotal ?? ''}`)
  if (summary.gates && (!summary.gates.mine || !summary.gates.carrier)) {
    doc.fillColor('#B45309').text(
      'Note: one or more documents did not fully reconcile against printed totals; figures are best available.'
    )
  }
  doc.moveDown(0.8)

  // Room rollups
  section(doc, 'Totals by room')
  for (const rollup of report.rollups ?? []) {
    row(doc, [
      [rollup.room, 200],
      [fmt(rollup.mineRcvCents), 100],
      [fmt(rollup.carrierRcvCents), 100],
      [fmt(rollup.deltaRcvCents), 100],
    ])
  }
  doc.moveDown(0.8)

  // Buckets
  const missing: ExportItem[] = (report.mineOnly ?? []).map((item: any) => ({
    room: item.room,
    code: item.catalog?.code ?? null,
    description: item.description,
    mineQty: `${item.quantity} ${item.unit}`,
    carrierQty: '—',
    deltaCents: item.rcvCents,
  }))
  const differences: ExportItem[] = (report.pairs ?? [])
    .filter((pair: any) => pair.rcvDeltaCents !== 0 || pair.qtyDelta !== 0)
    .map((pair: any) => ({
      room: pair.mine.room,
      code: pair.mine.catalog?.code ?? null,
      description: pair.mine.description,
      mineQty: `${pair.mine.quantity} ${pair.mine.unit}`,
      carrierQty: `${pair.carrier.quantity} ${pair.carrier.unit}`,
      deltaCents: pair.rcvDeltaCents,
    }))

  bucket(doc, 'Items missing from the carrier estimate', missing)
  bucket(doc, 'Items priced or measured differently', differences)

  // Provenance
  doc.moveDown(0.8)
  doc.font('Helvetica').fontSize(8.5).fillColor('#777777')
  const counts = summary.counts ?? {}
  doc.text(
    `Method: both estimates parsed deterministically and reconciled against their own printed totals; ` +
      `line items matched by Xactimate code and room (${counts.matched ?? 0} matched, ` +
      `${counts.mineOnly ?? 0} in ours only, ${counts.carrierOnly ?? 0} in carrier's only). ` +
      `All arithmetic computed programmatically. Generated by Manny's Toolbox.`
  )

  doc.end()
  return done
}

function section(doc: PDFKit.PDFDocument, title: string): void {
  ensureSpace(doc, 60)
  doc.font('Helvetica-Bold').fontSize(11.5).fillColor('#000000').text(title)
  doc
    .moveTo(doc.page.margins.left, doc.y + 2)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y + 2)
    .strokeColor('#BBBBBB')
    .stroke()
  doc.moveDown(0.4)
}

function bucket(doc: PDFKit.PDFDocument, title: string, items: ExportItem[]): void {
  if (items.length === 0) return
  const total = items.reduce((sum, item) => sum + item.deltaCents, 0)
  section(doc, `${title} — ${items.length} items, ${fmt(total)}`)
  const sorted = [...items].sort((a, b) => Math.abs(b.deltaCents) - Math.abs(a.deltaCents))
  for (const item of sorted) {
    row(doc, [
      [item.room, 90],
      [item.code ?? '', 55],
      [item.description, 205],
      [item.mineQty, 70],
      [item.deltaCents === 0 ? '' : fmt(item.deltaCents), 80],
    ])
  }
  doc.moveDown(0.6)
}

function row(doc: PDFKit.PDFDocument, cells: [string, number][]): void {
  ensureSpace(doc, 24)
  const y = doc.y
  let x = doc.page.margins.left
  doc.font('Helvetica').fontSize(8.5).fillColor('#222222')
  for (const [text, width] of cells) {
    doc.text(text, x, y, { width: width - 6, height: 20, ellipsis: true, lineBreak: false })
    x += width
  }
  doc.y = y + 13
  doc.x = doc.page.margins.left
}

function ensureSpace(doc: PDFKit.PDFDocument, needed: number): void {
  if (doc.y + needed > doc.page.height - doc.page.margins.bottom) {
    doc.addPage()
  }
}
